### ISSUE TITLE
Need to add Copyright information 

### ISSUE THREAD

**Issue by tumashu** [tumashu/pyim-greatdict#1]

**Comment by bennyandresen** [comment]
This project is currently lacking a clearly stated free license.

Please consider adding one. :-)

Reference: https://github.com/emacsmirror/epkg-reports/blob/master/licenses-details.org

**Comment by tumashu** [comment]
sorry, I do not know the dict's licence, i just know it is a free dict from the origin author, more detail is in README

**Comment by tarsius** [comment]
Do you know who `dict`'s authors are and could ask them for clarification?

**Comment by tumashu** [comment]
I have contacted with the author， but he have no interesting to do this job， and the most important is that he has forgot this toy dict's details。

**Comment by tumashu** [comment]
Maybe it is the time I obsolote this package

**Comment by tarsius** [comment]
I don't know, but I am afraid I will have to remove it from the Emacsmirror.

**Comment by tumashu** [comment]
just do it

**Comment by tarsius** [comment]
done
