### ISSUE TITLE
可以把词库解压吗，这样emacs到windows电脑上用的时候不用担心解压词库

### ISSUE THREAD

**Issue by yxsongbo** [tumashu/pyim-greatdict#2]
还可以在老机器上提升速度

**Comment by tumashu** [comment]
可以，不过你需要手动操作，因为解压缩后的词库一般都很大， greatdict 解压缩后有80多兆，这么大的文件 github 是有限制的，所以我选择压缩，你可以提取里面的pyim文件，用 pyim-dicts-manager 手动管理

**Comment by tumashu** [comment]
这个issue我关闭了
