### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by iamxiatian** [tumashu/pyim-greatdict#3]
加入这个大词库后，选词效果好多了，感谢作者的努力！

**Comment by tumashu** [comment]
我只是打包一下，最应该感谢的是 WenLiang Xiao 和  刘邵博 两个同学，另外要注意，这个词库很大，比较占内存。

**Comment by tumashu** [comment]
我只是打包一下，最应该感谢的是 WenLiang Xiao 和  刘邵博 两个同学，另外要注意，这个词库很大，比较占内存。
