### ISSUE TITLE
There is no package pyim-greatdict in melpa?

### ISSUE THREAD

**Issue by liuchong** [tumashu/pyim-greatdict#4]
Just checked that there no such package "pyim-greatdict" in melpa.org, anything is wrong?
Cannot type chinese now...sorry 😹

**Comment by tumashu** [comment]
哎，因为greatdict没法明确版权，被 melpa 管理员暂时删除了。。。。先暂时用basedict吧

**Comment by liuchong** [comment]
一个悲伤的故事 😹 
我自己下载了

**Comment by liuchong** [comment]
可以使用quelpa来安装：https://github.com/tumashu/pyim-greatdict/pull/5
